apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  backendType: {{ external_secrets__backend_type }}
  roleArn: {{ role_arn__external_secrets__oauth2_proxy }}
  data:
  - key: {{ external_secret__oauth2_proxy__name }}
    name: client-id
    property: {{ external_secret__oauth2_proxy__oidc_client_id }}
  - key: {{ external_secret__oauth2_proxy__name }}
    name: client-secret
    property: {{ external_secret__oauth2_proxy__oidc_client_secret }}
  - key: {{ external_secret__oauth2_proxy__name }}
    name: cookie-secret
    property: {{ external_secret__oauth2_proxy__oidc_cookie_secret }}



