apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gcr-json-key
  namespace: docs
spec:
  backendType: {{ external_secrets__backend_type }}
  roleArn: {{ role_arn__external_secrets__docs }}
  region: {{ aws_region }}
  template:
    type: kubernetes.io/dockerconfigjson
  data:
  - key: {{ external_secret__docs__name }}
    property: {{ external_secret__docs__property__gcr_json_key }}
    name: .dockerconfigjson



