
apiVersion: v1
kind: Service
metadata:
  name: rok-docs-develop
  labels:
    app: rok-docs-develop
spec:
  type: NodePort
  selector:
    app: rok-docs-develop
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rok-docs-develop
  labels:
    app: rok-docs-develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rok-docs-develop
  template:
    metadata:
      labels:
        app: rok-docs-develop
    spec:
      serviceAccountName: gcr-reader
      containers:
      - name: rok-docs
        image: gcr.io/arrikto-playground/rok-docs-internal:develop-l0-release-1.5-pre-4-g50ad3309b
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 1m
        volumeMounts:
        - name: internal-docs-arrikto-com-versions
          mountPath: /usr/share/nginx/html/_static/versions-dict.js
          subPath: versions.js
      volumes:
      - name: internal-docs-arrikto-com-versions
        configMap:
          name: {{ docs_host__internal }}.versions
