apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  labels:
    name: kubernetes-external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubernetes-external-secrets
  template:
    metadata:
      labels:
        name: kubernetes-external-secrets
    spec:
      serviceAccountName: external-secrets
      containers:
      - name: kubernetes-external-secrets
        image: ghcr.io/external-secrets/kubernetes-external-secrets:7.2.1
        imagePullPolicy: IfNotPresent
        resources: {}
        env:
        - name: AWS_DEFAULT_REGION
          value: {{ aws_region }}
        - name: AWS_REGION
          value: {{ aws_region }}
        - name: LOG_LEVEL
          value: info
        - name: LOG_MESSAGE_KEY
          value: msg
        - name: POLLER_INTERVAL_MILLISECONDS
          value: '10000'
        - name: WATCH_TIMEOUT
          value: '60000'
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
